### ISSUE TITLE
Create new worker for airflow 2.0.0

### ISSUE THREAD

**Issue by wilson-ip** [xnuinside/airflow_in_docker_compose#9]
When I try to create a new worker for celery executor with the following `.yml`. The webserver died.
```
services:
  worker_2:
    image: apache/airflow:2.0.0-python3.8
    env_file:
      - .env
    volumes:
      - ./airflow_files/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./files:/opt/airflow/files
      - /var/run/docker.sock:/var/run/docker.sock
    command: celery worker
    deploy:
      restart_policy:
        condition: on-failure
        delay: 8s
        max_attempts: 3
    networks:
      - airflow
```
![Screenshot 2021-01-11 at 2 34 17 PM](https://user-images.githubusercontent.com/2383680/104152543-d6873480-541a-11eb-852d-2d56dbdee76f.png)

Do you know how to scale out with the airflow 2.0.0 image?
